packages:
  - 'apps/*'
  - 'packages/domains/*'
  - 'packages/presentation/*'
  - 'packages/infrastructure/*'
  - 'packages/contracts/*'
  - 'packages/runtime/*'
  - 'packages/config/env'
  - 'packages/config/tailwind'
