/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from "@payloadcms/db-postgres";
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  text,
  varchar,
  jsonb,
  boolean,
  serial,
  timestamp,
  numeric,
  type AnyPgColumn,
  pgEnum,
} from "@payloadcms/db-postgres/drizzle/pg-core";
import { sql, relations } from "@payloadcms/db-postgres/drizzle";
export const enum_pages_blocks_hero_cta_link_type = pgEnum(
  "enum_pages_blocks_hero_cta_link_type",
  ["url", "page"],
);
export const enum_pages_blocks_cta_button_link_type = pgEnum(
  "enum_pages_blocks_cta_button_link_type",
  ["url", "page"],
);
export const enum_pages_status = pgEnum("enum_pages_status", [
  "draft",
  "published",
]);
export const enum__pages_v_blocks_hero_cta_link_type = pgEnum(
  "enum__pages_v_blocks_hero_cta_link_type",
  ["url", "page"],
);
export const enum__pages_v_blocks_cta_button_link_type = pgEnum(
  "enum__pages_v_blocks_cta_button_link_type",
  ["url", "page"],
);
export const enum__pages_v_version_status = pgEnum(
  "enum__pages_v_version_status",
  ["draft", "published"],
);
export const enum_users_role = pgEnum("enum_users_role", [
  "admin",
  "designer",
  "contentEditor",
  "engineer",
]);
export const enum_design_token_sets_tokens_category = pgEnum(
  "enum_design_token_sets_tokens_category",
  [
    "color",
    "space",
    "size",
    "radius",
    "typography",
    "shadow",
    "border",
    "zIndex",
    "opacity",
    "transition",
    "breakpoint",
    "container",
  ],
);
export const enum_design_token_sets_tokens_mode = pgEnum(
  "enum_design_token_sets_tokens_mode",
  ["light", "dark"],
);
export const enum_design_token_sets_status = pgEnum(
  "enum_design_token_sets_status",
  ["draft", "published"],
);
export const enum__design_token_sets_v_version_tokens_category = pgEnum(
  "enum__design_token_sets_v_version_tokens_category",
  [
    "color",
    "space",
    "size",
    "radius",
    "typography",
    "shadow",
    "border",
    "zIndex",
    "opacity",
    "transition",
    "breakpoint",
    "container",
  ],
);
export const enum__design_token_sets_v_version_tokens_mode = pgEnum(
  "enum__design_token_sets_v_version_tokens_mode",
  ["light", "dark"],
);
export const enum__design_token_sets_v_version_status = pgEnum(
  "enum__design_token_sets_v_version_status",
  ["draft", "published"],
);
export const enum_components_block_type = pgEnum("enum_components_block_type", [
  "hero",
  "feature",
  "cta",
  "content",
]);
export const enum_components_status = pgEnum("enum_components_status", [
  "draft",
  "published",
]);
export const enum__components_v_version_block_type = pgEnum(
  "enum__components_v_version_block_type",
  ["hero", "feature", "cta", "content"],
);
export const enum__components_v_version_status = pgEnum(
  "enum__components_v_version_status",
  ["draft", "published"],
);
export const enum_page_compositions_status = pgEnum(
  "enum_page_compositions_status",
  ["draft", "published"],
);
export const enum__page_compositions_v_version_status = pgEnum(
  "enum__page_compositions_v_version_status",
  ["draft", "published"],
);
export const enum_payload_folders_folder_type = pgEnum(
  "enum_payload_folders_folder_type",
  ["components"],
);
export const enum_design_system_settings_active_color_mode = pgEnum(
  "enum_design_system_settings_active_color_mode",
  ["light", "dark"],
);

export const pages_blocks_hero = pgTable(
  "pages_blocks_hero",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    _path: text("_path").notNull(),
    id: varchar("id").primaryKey(),
    design: integer("design_id").references(() => components.id, {
      onDelete: "set null",
    }),
    heading: varchar("heading"),
    body: jsonb("body"),
    image: integer("image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    cta_label: varchar("cta_label"),
    cta_linkType:
      enum_pages_blocks_hero_cta_link_type("cta_link_type").default("url"),
    cta_url: varchar("cta_url"),
    cta_page: integer("cta_page_id").references(() => pages.id, {
      onDelete: "set null",
    }),
    cta_openInNewTab: boolean("cta_open_in_new_tab").default(false),
    blockName: varchar("block_name"),
  },
  (columns) => [
    index("pages_blocks_hero_order_idx").on(columns._order),
    index("pages_blocks_hero_parent_id_idx").on(columns._parentID),
    index("pages_blocks_hero_path_idx").on(columns._path),
    index("pages_blocks_hero_design_idx").on(columns.design),
    index("pages_blocks_hero_image_idx").on(columns.image),
    index("pages_blocks_hero_cta_cta_page_idx").on(columns.cta_page),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [pages.id],
      name: "pages_blocks_hero_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const pages_blocks_feature = pgTable(
  "pages_blocks_feature",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    _path: text("_path").notNull(),
    id: varchar("id").primaryKey(),
    design: integer("design_id").references(() => components.id, {
      onDelete: "set null",
    }),
    heading: varchar("heading"),
    body: jsonb("body"),
    image: integer("image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    blockName: varchar("block_name"),
  },
  (columns) => [
    index("pages_blocks_feature_order_idx").on(columns._order),
    index("pages_blocks_feature_parent_id_idx").on(columns._parentID),
    index("pages_blocks_feature_path_idx").on(columns._path),
    index("pages_blocks_feature_design_idx").on(columns.design),
    index("pages_blocks_feature_image_idx").on(columns.image),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [pages.id],
      name: "pages_blocks_feature_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const pages_blocks_cta = pgTable(
  "pages_blocks_cta",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    _path: text("_path").notNull(),
    id: varchar("id").primaryKey(),
    design: integer("design_id").references(() => components.id, {
      onDelete: "set null",
    }),
    heading: varchar("heading"),
    body: jsonb("body"),
    button_label: varchar("button_label"),
    button_linkType:
      enum_pages_blocks_cta_button_link_type("button_link_type").default("url"),
    button_url: varchar("button_url"),
    button_page: integer("button_page_id").references(() => pages.id, {
      onDelete: "set null",
    }),
    button_openInNewTab: boolean("button_open_in_new_tab").default(false),
    blockName: varchar("block_name"),
  },
  (columns) => [
    index("pages_blocks_cta_order_idx").on(columns._order),
    index("pages_blocks_cta_parent_id_idx").on(columns._parentID),
    index("pages_blocks_cta_path_idx").on(columns._path),
    index("pages_blocks_cta_design_idx").on(columns.design),
    index("pages_blocks_cta_button_button_page_idx").on(columns.button_page),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [pages.id],
      name: "pages_blocks_cta_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const pages_blocks_content = pgTable(
  "pages_blocks_content",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    _path: text("_path").notNull(),
    id: varchar("id").primaryKey(),
    design: integer("design_id").references(() => components.id, {
      onDelete: "set null",
    }),
    body: jsonb("body"),
    blockName: varchar("block_name"),
  },
  (columns) => [
    index("pages_blocks_content_order_idx").on(columns._order),
    index("pages_blocks_content_parent_id_idx").on(columns._parentID),
    index("pages_blocks_content_path_idx").on(columns._path),
    index("pages_blocks_content_design_idx").on(columns.design),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [pages.id],
      name: "pages_blocks_content_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const pages_content_slots = pgTable(
  "pages_content_slots",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    slotId: varchar("slot_id"),
  },
  (columns) => [
    index("pages_content_slots_order_idx").on(columns._order),
    index("pages_content_slots_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [pages.id],
      name: "pages_content_slots_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const pages = pgTable(
  "pages",
  {
    id: serial("id").primaryKey(),
    title: varchar("title"),
    slug: varchar("slug"),
    seoDescription: jsonb("seo_description"),
    socialShareText: jsonb("social_share_text"),
    pageComposition: integer("page_composition_id").references(
      () => page_compositions.id,
      {
        onDelete: "set null",
      },
    ),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    _status: enum_pages_status("_status").default("draft"),
  },
  (columns) => [
    uniqueIndex("pages_slug_idx").on(columns.slug),
    index("pages_page_composition_idx").on(columns.pageComposition),
    index("pages_updated_at_idx").on(columns.updatedAt),
    index("pages_created_at_idx").on(columns.createdAt),
    index("pages__status_idx").on(columns._status),
  ],
);

export const _pages_v_blocks_hero = pgTable(
  "_pages_v_blocks_hero",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    _path: text("_path").notNull(),
    id: serial("id").primaryKey(),
    design: integer("design_id").references(() => components.id, {
      onDelete: "set null",
    }),
    heading: varchar("heading"),
    body: jsonb("body"),
    image: integer("image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    cta_label: varchar("cta_label"),
    cta_linkType:
      enum__pages_v_blocks_hero_cta_link_type("cta_link_type").default("url"),
    cta_url: varchar("cta_url"),
    cta_page: integer("cta_page_id").references(() => pages.id, {
      onDelete: "set null",
    }),
    cta_openInNewTab: boolean("cta_open_in_new_tab").default(false),
    _uuid: varchar("_uuid"),
    blockName: varchar("block_name"),
  },
  (columns) => [
    index("_pages_v_blocks_hero_order_idx").on(columns._order),
    index("_pages_v_blocks_hero_parent_id_idx").on(columns._parentID),
    index("_pages_v_blocks_hero_path_idx").on(columns._path),
    index("_pages_v_blocks_hero_design_idx").on(columns.design),
    index("_pages_v_blocks_hero_image_idx").on(columns.image),
    index("_pages_v_blocks_hero_cta_cta_page_idx").on(columns.cta_page),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [_pages_v.id],
      name: "_pages_v_blocks_hero_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const _pages_v_blocks_feature = pgTable(
  "_pages_v_blocks_feature",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    _path: text("_path").notNull(),
    id: serial("id").primaryKey(),
    design: integer("design_id").references(() => components.id, {
      onDelete: "set null",
    }),
    heading: varchar("heading"),
    body: jsonb("body"),
    image: integer("image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    _uuid: varchar("_uuid"),
    blockName: varchar("block_name"),
  },
  (columns) => [
    index("_pages_v_blocks_feature_order_idx").on(columns._order),
    index("_pages_v_blocks_feature_parent_id_idx").on(columns._parentID),
    index("_pages_v_blocks_feature_path_idx").on(columns._path),
    index("_pages_v_blocks_feature_design_idx").on(columns.design),
    index("_pages_v_blocks_feature_image_idx").on(columns.image),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [_pages_v.id],
      name: "_pages_v_blocks_feature_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const _pages_v_blocks_cta = pgTable(
  "_pages_v_blocks_cta",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    _path: text("_path").notNull(),
    id: serial("id").primaryKey(),
    design: integer("design_id").references(() => components.id, {
      onDelete: "set null",
    }),
    heading: varchar("heading"),
    body: jsonb("body"),
    button_label: varchar("button_label"),
    button_linkType:
      enum__pages_v_blocks_cta_button_link_type("button_link_type").default(
        "url",
      ),
    button_url: varchar("button_url"),
    button_page: integer("button_page_id").references(() => pages.id, {
      onDelete: "set null",
    }),
    button_openInNewTab: boolean("button_open_in_new_tab").default(false),
    _uuid: varchar("_uuid"),
    blockName: varchar("block_name"),
  },
  (columns) => [
    index("_pages_v_blocks_cta_order_idx").on(columns._order),
    index("_pages_v_blocks_cta_parent_id_idx").on(columns._parentID),
    index("_pages_v_blocks_cta_path_idx").on(columns._path),
    index("_pages_v_blocks_cta_design_idx").on(columns.design),
    index("_pages_v_blocks_cta_button_button_page_idx").on(columns.button_page),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [_pages_v.id],
      name: "_pages_v_blocks_cta_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const _pages_v_blocks_content = pgTable(
  "_pages_v_blocks_content",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    _path: text("_path").notNull(),
    id: serial("id").primaryKey(),
    design: integer("design_id").references(() => components.id, {
      onDelete: "set null",
    }),
    body: jsonb("body"),
    _uuid: varchar("_uuid"),
    blockName: varchar("block_name"),
  },
  (columns) => [
    index("_pages_v_blocks_content_order_idx").on(columns._order),
    index("_pages_v_blocks_content_parent_id_idx").on(columns._parentID),
    index("_pages_v_blocks_content_path_idx").on(columns._path),
    index("_pages_v_blocks_content_design_idx").on(columns.design),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [_pages_v.id],
      name: "_pages_v_blocks_content_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const _pages_v_version_content_slots = pgTable(
  "_pages_v_version_content_slots",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: serial("id").primaryKey(),
    slotId: varchar("slot_id"),
    _uuid: varchar("_uuid"),
  },
  (columns) => [
    index("_pages_v_version_content_slots_order_idx").on(columns._order),
    index("_pages_v_version_content_slots_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [_pages_v.id],
      name: "_pages_v_version_content_slots_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const _pages_v = pgTable(
  "_pages_v",
  {
    id: serial("id").primaryKey(),
    parent: integer("parent_id").references(() => pages.id, {
      onDelete: "set null",
    }),
    version_title: varchar("version_title"),
    version_slug: varchar("version_slug"),
    version_seoDescription: jsonb("version_seo_description"),
    version_socialShareText: jsonb("version_social_share_text"),
    version_pageComposition: integer("version_page_composition_id").references(
      () => page_compositions.id,
      {
        onDelete: "set null",
      },
    ),
    version_updatedAt: timestamp("version_updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp("version_created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version__status:
      enum__pages_v_version_status("version__status").default("draft"),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    latest: boolean("latest"),
  },
  (columns) => [
    index("_pages_v_parent_idx").on(columns.parent),
    index("_pages_v_version_version_slug_idx").on(columns.version_slug),
    index("_pages_v_version_version_page_composition_idx").on(
      columns.version_pageComposition,
    ),
    index("_pages_v_version_version_updated_at_idx").on(
      columns.version_updatedAt,
    ),
    index("_pages_v_version_version_created_at_idx").on(
      columns.version_createdAt,
    ),
    index("_pages_v_version_version__status_idx").on(columns.version__status),
    index("_pages_v_created_at_idx").on(columns.createdAt),
    index("_pages_v_updated_at_idx").on(columns.updatedAt),
    index("_pages_v_latest_idx").on(columns.latest),
  ],
);

export const users_sessions = pgTable(
  "users_sessions",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    expiresAt: timestamp("expires_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index("users_sessions_order_idx").on(columns._order),
    index("users_sessions_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [users.id],
      name: "users_sessions_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const users = pgTable(
  "users",
  {
    id: serial("id").primaryKey(),
    role: enum_users_role("role").notNull().default("contentEditor"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    email: varchar("email").notNull(),
    resetPasswordToken: varchar("reset_password_token"),
    resetPasswordExpiration: timestamp("reset_password_expiration", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar("salt"),
    hash: varchar("hash"),
    loginAttempts: numeric("login_attempts", { mode: "number" }).default(0),
    lockUntil: timestamp("lock_until", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => [
    index("users_updated_at_idx").on(columns.updatedAt),
    index("users_created_at_idx").on(columns.createdAt),
    uniqueIndex("users_email_idx").on(columns.email),
  ],
);

export const media = pgTable(
  "media",
  {
    id: serial("id").primaryKey(),
    alt: varchar("alt").notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    url: varchar("url"),
    thumbnailURL: varchar("thumbnail_u_r_l"),
    filename: varchar("filename"),
    mimeType: varchar("mime_type"),
    filesize: numeric("filesize", { mode: "number" }),
    width: numeric("width", { mode: "number" }),
    height: numeric("height", { mode: "number" }),
    focalX: numeric("focal_x", { mode: "number" }),
    focalY: numeric("focal_y", { mode: "number" }),
  },
  (columns) => [
    index("media_updated_at_idx").on(columns.updatedAt),
    index("media_created_at_idx").on(columns.createdAt),
    uniqueIndex("media_filename_idx").on(columns.filename),
  ],
);

export const design_token_sets_tokens = pgTable(
  "design_token_sets_tokens",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    key: varchar("key"),
    category: enum_design_token_sets_tokens_category("category"),
    mode: enum_design_token_sets_tokens_mode("mode").default("light"),
    resolvedValue: varchar("resolved_value"),
  },
  (columns) => [
    index("design_token_sets_tokens_order_idx").on(columns._order),
    index("design_token_sets_tokens_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [design_token_sets.id],
      name: "design_token_sets_tokens_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const design_token_sets = pgTable(
  "design_token_sets",
  {
    id: serial("id").primaryKey(),
    title: varchar("title"),
    scopeKey: varchar("scope_key"),
    hasBeenPublished: boolean("has_been_published").default(false),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    _status: enum_design_token_sets_status("_status").default("draft"),
  },
  (columns) => [
    uniqueIndex("design_token_sets_scope_key_idx").on(columns.scopeKey),
    index("design_token_sets_updated_at_idx").on(columns.updatedAt),
    index("design_token_sets_created_at_idx").on(columns.createdAt),
    index("design_token_sets__status_idx").on(columns._status),
  ],
);

export const _design_token_sets_v_version_tokens = pgTable(
  "_design_token_sets_v_version_tokens",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: serial("id").primaryKey(),
    key: varchar("key"),
    category: enum__design_token_sets_v_version_tokens_category("category"),
    mode: enum__design_token_sets_v_version_tokens_mode("mode").default(
      "light",
    ),
    resolvedValue: varchar("resolved_value"),
    _uuid: varchar("_uuid"),
  },
  (columns) => [
    index("_design_token_sets_v_version_tokens_order_idx").on(columns._order),
    index("_design_token_sets_v_version_tokens_parent_id_idx").on(
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [_design_token_sets_v.id],
      name: "_design_token_sets_v_version_tokens_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const _design_token_sets_v = pgTable(
  "_design_token_sets_v",
  {
    id: serial("id").primaryKey(),
    parent: integer("parent_id").references(() => design_token_sets.id, {
      onDelete: "set null",
    }),
    version_title: varchar("version_title"),
    version_scopeKey: varchar("version_scope_key"),
    version_hasBeenPublished: boolean("version_has_been_published").default(
      false,
    ),
    version_updatedAt: timestamp("version_updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp("version_created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version__status:
      enum__design_token_sets_v_version_status("version__status").default(
        "draft",
      ),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    latest: boolean("latest"),
  },
  (columns) => [
    index("_design_token_sets_v_parent_idx").on(columns.parent),
    index("_design_token_sets_v_version_version_scope_key_idx").on(
      columns.version_scopeKey,
    ),
    index("_design_token_sets_v_version_version_updated_at_idx").on(
      columns.version_updatedAt,
    ),
    index("_design_token_sets_v_version_version_created_at_idx").on(
      columns.version_createdAt,
    ),
    index("_design_token_sets_v_version_version__status_idx").on(
      columns.version__status,
    ),
    index("_design_token_sets_v_created_at_idx").on(columns.createdAt),
    index("_design_token_sets_v_updated_at_idx").on(columns.updatedAt),
    index("_design_token_sets_v_latest_idx").on(columns.latest),
  ],
);

export const components = pgTable(
  "components",
  {
    id: serial("id").primaryKey(),
    displayName: varchar("display_name"),
    key: varchar("key"),
    blockType: enum_components_block_type("block_type"),
    composition: jsonb("composition"),
    lastTouchedBy: integer("last_touched_by_id").references(() => users.id, {
      onDelete: "set null",
    }),
    folder: integer("folder_id").references(() => payload_folders.id, {
      onDelete: "set null",
    }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    _status: enum_components_status("_status").default("draft"),
  },
  (columns) => [
    uniqueIndex("components_key_idx").on(columns.key),
    index("components_block_type_idx").on(columns.blockType),
    index("components_last_touched_by_idx").on(columns.lastTouchedBy),
    index("components_folder_idx").on(columns.folder),
    index("components_updated_at_idx").on(columns.updatedAt),
    index("components_created_at_idx").on(columns.createdAt),
    index("components__status_idx").on(columns._status),
  ],
);

export const _components_v = pgTable(
  "_components_v",
  {
    id: serial("id").primaryKey(),
    parent: integer("parent_id").references(() => components.id, {
      onDelete: "set null",
    }),
    version_displayName: varchar("version_display_name"),
    version_key: varchar("version_key"),
    version_blockType:
      enum__components_v_version_block_type("version_block_type"),
    version_composition: jsonb("version_composition"),
    version_lastTouchedBy: integer("version_last_touched_by_id").references(
      () => users.id,
      {
        onDelete: "set null",
      },
    ),
    version_folder: integer("version_folder_id").references(
      () => payload_folders.id,
      {
        onDelete: "set null",
      },
    ),
    version_updatedAt: timestamp("version_updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp("version_created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version__status:
      enum__components_v_version_status("version__status").default("draft"),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    latest: boolean("latest"),
  },
  (columns) => [
    index("_components_v_parent_idx").on(columns.parent),
    index("_components_v_version_version_key_idx").on(columns.version_key),
    index("_components_v_version_version_block_type_idx").on(
      columns.version_blockType,
    ),
    index("_components_v_version_version_last_touched_by_idx").on(
      columns.version_lastTouchedBy,
    ),
    index("_components_v_version_version_folder_idx").on(
      columns.version_folder,
    ),
    index("_components_v_version_version_updated_at_idx").on(
      columns.version_updatedAt,
    ),
    index("_components_v_version_version_created_at_idx").on(
      columns.version_createdAt,
    ),
    index("_components_v_version_version__status_idx").on(
      columns.version__status,
    ),
    index("_components_v_created_at_idx").on(columns.createdAt),
    index("_components_v_updated_at_idx").on(columns.updatedAt),
    index("_components_v_latest_idx").on(columns.latest),
  ],
);

export const page_compositions = pgTable(
  "page_compositions",
  {
    id: serial("id").primaryKey(),
    title: varchar("title"),
    slug: varchar("slug"),
    composition: jsonb("composition"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    _status: enum_page_compositions_status("_status").default("draft"),
  },
  (columns) => [
    uniqueIndex("page_compositions_slug_idx").on(columns.slug),
    index("page_compositions_updated_at_idx").on(columns.updatedAt),
    index("page_compositions_created_at_idx").on(columns.createdAt),
    index("page_compositions__status_idx").on(columns._status),
  ],
);

export const _page_compositions_v = pgTable(
  "_page_compositions_v",
  {
    id: serial("id").primaryKey(),
    parent: integer("parent_id").references(() => page_compositions.id, {
      onDelete: "set null",
    }),
    version_title: varchar("version_title"),
    version_slug: varchar("version_slug"),
    version_composition: jsonb("version_composition"),
    version_updatedAt: timestamp("version_updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp("version_created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version__status:
      enum__page_compositions_v_version_status("version__status").default(
        "draft",
      ),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    latest: boolean("latest"),
  },
  (columns) => [
    index("_page_compositions_v_parent_idx").on(columns.parent),
    index("_page_compositions_v_version_version_slug_idx").on(
      columns.version_slug,
    ),
    index("_page_compositions_v_version_version_updated_at_idx").on(
      columns.version_updatedAt,
    ),
    index("_page_compositions_v_version_version_created_at_idx").on(
      columns.version_createdAt,
    ),
    index("_page_compositions_v_version_version__status_idx").on(
      columns.version__status,
    ),
    index("_page_compositions_v_created_at_idx").on(columns.createdAt),
    index("_page_compositions_v_updated_at_idx").on(columns.updatedAt),
    index("_page_compositions_v_latest_idx").on(columns.latest),
  ],
);

export const payload_kv = pgTable(
  "payload_kv",
  {
    id: serial("id").primaryKey(),
    key: varchar("key").notNull(),
    data: jsonb("data").notNull(),
  },
  (columns) => [uniqueIndex("payload_kv_key_idx").on(columns.key)],
);

export const payload_folders_folder_type = pgTable(
  "payload_folders_folder_type",
  {
    order: integer("order").notNull(),
    parent: integer("parent_id").notNull(),
    value: enum_payload_folders_folder_type("value"),
    id: serial("id").primaryKey(),
  },
  (columns) => [
    index("payload_folders_folder_type_order_idx").on(columns.order),
    index("payload_folders_folder_type_parent_idx").on(columns.parent),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_folders.id],
      name: "payload_folders_folder_type_parent_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_folders = pgTable(
  "payload_folders",
  {
    id: serial("id").primaryKey(),
    name: varchar("name").notNull(),
    folder: integer("folder_id").references(
      (): AnyPgColumn => payload_folders.id,
      {
        onDelete: "set null",
      },
    ),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_folders_name_idx").on(columns.name),
    index("payload_folders_folder_idx").on(columns.folder),
    index("payload_folders_updated_at_idx").on(columns.updatedAt),
    index("payload_folders_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_locked_documents = pgTable(
  "payload_locked_documents",
  {
    id: serial("id").primaryKey(),
    globalSlug: varchar("global_slug"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_locked_documents_global_slug_idx").on(columns.globalSlug),
    index("payload_locked_documents_updated_at_idx").on(columns.updatedAt),
    index("payload_locked_documents_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_locked_documents_rels = pgTable(
  "payload_locked_documents_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    pagesID: integer("pages_id"),
    usersID: integer("users_id"),
    mediaID: integer("media_id"),
    "design-token-setsID": integer("design_token_sets_id"),
    componentsID: integer("components_id"),
    "page-compositionsID": integer("page_compositions_id"),
    "payload-foldersID": integer("payload_folders_id"),
  },
  (columns) => [
    index("payload_locked_documents_rels_order_idx").on(columns.order),
    index("payload_locked_documents_rels_parent_idx").on(columns.parent),
    index("payload_locked_documents_rels_path_idx").on(columns.path),
    index("payload_locked_documents_rels_pages_id_idx").on(columns.pagesID),
    index("payload_locked_documents_rels_users_id_idx").on(columns.usersID),
    index("payload_locked_documents_rels_media_id_idx").on(columns.mediaID),
    index("payload_locked_documents_rels_design_token_sets_id_idx").on(
      columns["design-token-setsID"],
    ),
    index("payload_locked_documents_rels_components_id_idx").on(
      columns.componentsID,
    ),
    index("payload_locked_documents_rels_page_compositions_id_idx").on(
      columns["page-compositionsID"],
    ),
    index("payload_locked_documents_rels_payload_folders_id_idx").on(
      columns["payload-foldersID"],
    ),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_locked_documents.id],
      name: "payload_locked_documents_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["pagesID"]],
      foreignColumns: [pages.id],
      name: "payload_locked_documents_rels_pages_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_locked_documents_rels_users_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["mediaID"]],
      foreignColumns: [media.id],
      name: "payload_locked_documents_rels_media_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["design-token-setsID"]],
      foreignColumns: [design_token_sets.id],
      name: "payload_locked_documents_rels_design_token_sets_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["componentsID"]],
      foreignColumns: [components.id],
      name: "payload_locked_documents_rels_components_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["page-compositionsID"]],
      foreignColumns: [page_compositions.id],
      name: "payload_locked_documents_rels_page_compositions_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["payload-foldersID"]],
      foreignColumns: [payload_folders.id],
      name: "payload_locked_documents_rels_payload_folders_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_preferences = pgTable(
  "payload_preferences",
  {
    id: serial("id").primaryKey(),
    key: varchar("key"),
    value: jsonb("value"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_preferences_key_idx").on(columns.key),
    index("payload_preferences_updated_at_idx").on(columns.updatedAt),
    index("payload_preferences_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_preferences_rels = pgTable(
  "payload_preferences_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: integer("users_id"),
  },
  (columns) => [
    index("payload_preferences_rels_order_idx").on(columns.order),
    index("payload_preferences_rels_parent_idx").on(columns.parent),
    index("payload_preferences_rels_path_idx").on(columns.path),
    index("payload_preferences_rels_users_id_idx").on(columns.usersID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_preferences.id],
      name: "payload_preferences_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_preferences_rels_users_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_migrations = pgTable(
  "payload_migrations",
  {
    id: serial("id").primaryKey(),
    name: varchar("name"),
    batch: numeric("batch", { mode: "number" }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_migrations_updated_at_idx").on(columns.updatedAt),
    index("payload_migrations_created_at_idx").on(columns.createdAt),
  ],
);

export const design_system_settings = pgTable(
  "design_system_settings",
  {
    id: serial("id").primaryKey(),
    defaultTokenSet: integer("default_token_set_id").references(
      () => design_token_sets.id,
      {
        onDelete: "set null",
      },
    ),
    activeBrandKey: varchar("active_brand_key"),
    activeColorMode: enum_design_system_settings_active_color_mode(
      "active_color_mode",
    )
      .notNull()
      .default("light"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => [
    index("design_system_settings_default_token_set_idx").on(
      columns.defaultTokenSet,
    ),
  ],
);

export const relations_pages_blocks_hero = relations(
  pages_blocks_hero,
  ({ one }) => ({
    _parentID: one(pages, {
      fields: [pages_blocks_hero._parentID],
      references: [pages.id],
      relationName: "_blocks_hero",
    }),
    design: one(components, {
      fields: [pages_blocks_hero.design],
      references: [components.id],
      relationName: "design",
    }),
    image: one(media, {
      fields: [pages_blocks_hero.image],
      references: [media.id],
      relationName: "image",
    }),
    cta_page: one(pages, {
      fields: [pages_blocks_hero.cta_page],
      references: [pages.id],
      relationName: "cta_page",
    }),
  }),
);
export const relations_pages_blocks_feature = relations(
  pages_blocks_feature,
  ({ one }) => ({
    _parentID: one(pages, {
      fields: [pages_blocks_feature._parentID],
      references: [pages.id],
      relationName: "_blocks_feature",
    }),
    design: one(components, {
      fields: [pages_blocks_feature.design],
      references: [components.id],
      relationName: "design",
    }),
    image: one(media, {
      fields: [pages_blocks_feature.image],
      references: [media.id],
      relationName: "image",
    }),
  }),
);
export const relations_pages_blocks_cta = relations(
  pages_blocks_cta,
  ({ one }) => ({
    _parentID: one(pages, {
      fields: [pages_blocks_cta._parentID],
      references: [pages.id],
      relationName: "_blocks_cta",
    }),
    design: one(components, {
      fields: [pages_blocks_cta.design],
      references: [components.id],
      relationName: "design",
    }),
    button_page: one(pages, {
      fields: [pages_blocks_cta.button_page],
      references: [pages.id],
      relationName: "button_page",
    }),
  }),
);
export const relations_pages_blocks_content = relations(
  pages_blocks_content,
  ({ one }) => ({
    _parentID: one(pages, {
      fields: [pages_blocks_content._parentID],
      references: [pages.id],
      relationName: "_blocks_content",
    }),
    design: one(components, {
      fields: [pages_blocks_content.design],
      references: [components.id],
      relationName: "design",
    }),
  }),
);
export const relations_pages_content_slots = relations(
  pages_content_slots,
  ({ one }) => ({
    _parentID: one(pages, {
      fields: [pages_content_slots._parentID],
      references: [pages.id],
      relationName: "contentSlots",
    }),
  }),
);
export const relations_pages = relations(pages, ({ one, many }) => ({
  pageComposition: one(page_compositions, {
    fields: [pages.pageComposition],
    references: [page_compositions.id],
    relationName: "pageComposition",
  }),
  _blocks_hero: many(pages_blocks_hero, {
    relationName: "_blocks_hero",
  }),
  _blocks_feature: many(pages_blocks_feature, {
    relationName: "_blocks_feature",
  }),
  _blocks_cta: many(pages_blocks_cta, {
    relationName: "_blocks_cta",
  }),
  _blocks_content: many(pages_blocks_content, {
    relationName: "_blocks_content",
  }),
  contentSlots: many(pages_content_slots, {
    relationName: "contentSlots",
  }),
}));
export const relations__pages_v_blocks_hero = relations(
  _pages_v_blocks_hero,
  ({ one }) => ({
    _parentID: one(_pages_v, {
      fields: [_pages_v_blocks_hero._parentID],
      references: [_pages_v.id],
      relationName: "_blocks_hero",
    }),
    design: one(components, {
      fields: [_pages_v_blocks_hero.design],
      references: [components.id],
      relationName: "design",
    }),
    image: one(media, {
      fields: [_pages_v_blocks_hero.image],
      references: [media.id],
      relationName: "image",
    }),
    cta_page: one(pages, {
      fields: [_pages_v_blocks_hero.cta_page],
      references: [pages.id],
      relationName: "cta_page",
    }),
  }),
);
export const relations__pages_v_blocks_feature = relations(
  _pages_v_blocks_feature,
  ({ one }) => ({
    _parentID: one(_pages_v, {
      fields: [_pages_v_blocks_feature._parentID],
      references: [_pages_v.id],
      relationName: "_blocks_feature",
    }),
    design: one(components, {
      fields: [_pages_v_blocks_feature.design],
      references: [components.id],
      relationName: "design",
    }),
    image: one(media, {
      fields: [_pages_v_blocks_feature.image],
      references: [media.id],
      relationName: "image",
    }),
  }),
);
export const relations__pages_v_blocks_cta = relations(
  _pages_v_blocks_cta,
  ({ one }) => ({
    _parentID: one(_pages_v, {
      fields: [_pages_v_blocks_cta._parentID],
      references: [_pages_v.id],
      relationName: "_blocks_cta",
    }),
    design: one(components, {
      fields: [_pages_v_blocks_cta.design],
      references: [components.id],
      relationName: "design",
    }),
    button_page: one(pages, {
      fields: [_pages_v_blocks_cta.button_page],
      references: [pages.id],
      relationName: "button_page",
    }),
  }),
);
export const relations__pages_v_blocks_content = relations(
  _pages_v_blocks_content,
  ({ one }) => ({
    _parentID: one(_pages_v, {
      fields: [_pages_v_blocks_content._parentID],
      references: [_pages_v.id],
      relationName: "_blocks_content",
    }),
    design: one(components, {
      fields: [_pages_v_blocks_content.design],
      references: [components.id],
      relationName: "design",
    }),
  }),
);
export const relations__pages_v_version_content_slots = relations(
  _pages_v_version_content_slots,
  ({ one }) => ({
    _parentID: one(_pages_v, {
      fields: [_pages_v_version_content_slots._parentID],
      references: [_pages_v.id],
      relationName: "version_contentSlots",
    }),
  }),
);
export const relations__pages_v = relations(_pages_v, ({ one, many }) => ({
  parent: one(pages, {
    fields: [_pages_v.parent],
    references: [pages.id],
    relationName: "parent",
  }),
  version_pageComposition: one(page_compositions, {
    fields: [_pages_v.version_pageComposition],
    references: [page_compositions.id],
    relationName: "version_pageComposition",
  }),
  _blocks_hero: many(_pages_v_blocks_hero, {
    relationName: "_blocks_hero",
  }),
  _blocks_feature: many(_pages_v_blocks_feature, {
    relationName: "_blocks_feature",
  }),
  _blocks_cta: many(_pages_v_blocks_cta, {
    relationName: "_blocks_cta",
  }),
  _blocks_content: many(_pages_v_blocks_content, {
    relationName: "_blocks_content",
  }),
  version_contentSlots: many(_pages_v_version_content_slots, {
    relationName: "version_contentSlots",
  }),
}));
export const relations_users_sessions = relations(
  users_sessions,
  ({ one }) => ({
    _parentID: one(users, {
      fields: [users_sessions._parentID],
      references: [users.id],
      relationName: "sessions",
    }),
  }),
);
export const relations_users = relations(users, ({ many }) => ({
  sessions: many(users_sessions, {
    relationName: "sessions",
  }),
}));
export const relations_media = relations(media, () => ({}));
export const relations_design_token_sets_tokens = relations(
  design_token_sets_tokens,
  ({ one }) => ({
    _parentID: one(design_token_sets, {
      fields: [design_token_sets_tokens._parentID],
      references: [design_token_sets.id],
      relationName: "tokens",
    }),
  }),
);
export const relations_design_token_sets = relations(
  design_token_sets,
  ({ many }) => ({
    tokens: many(design_token_sets_tokens, {
      relationName: "tokens",
    }),
  }),
);
export const relations__design_token_sets_v_version_tokens = relations(
  _design_token_sets_v_version_tokens,
  ({ one }) => ({
    _parentID: one(_design_token_sets_v, {
      fields: [_design_token_sets_v_version_tokens._parentID],
      references: [_design_token_sets_v.id],
      relationName: "version_tokens",
    }),
  }),
);
export const relations__design_token_sets_v = relations(
  _design_token_sets_v,
  ({ one, many }) => ({
    parent: one(design_token_sets, {
      fields: [_design_token_sets_v.parent],
      references: [design_token_sets.id],
      relationName: "parent",
    }),
    version_tokens: many(_design_token_sets_v_version_tokens, {
      relationName: "version_tokens",
    }),
  }),
);
export const relations_components = relations(components, ({ one }) => ({
  lastTouchedBy: one(users, {
    fields: [components.lastTouchedBy],
    references: [users.id],
    relationName: "lastTouchedBy",
  }),
  folder: one(payload_folders, {
    fields: [components.folder],
    references: [payload_folders.id],
    relationName: "folder",
  }),
}));
export const relations__components_v = relations(_components_v, ({ one }) => ({
  parent: one(components, {
    fields: [_components_v.parent],
    references: [components.id],
    relationName: "parent",
  }),
  version_lastTouchedBy: one(users, {
    fields: [_components_v.version_lastTouchedBy],
    references: [users.id],
    relationName: "version_lastTouchedBy",
  }),
  version_folder: one(payload_folders, {
    fields: [_components_v.version_folder],
    references: [payload_folders.id],
    relationName: "version_folder",
  }),
}));
export const relations_page_compositions = relations(
  page_compositions,
  () => ({}),
);
export const relations__page_compositions_v = relations(
  _page_compositions_v,
  ({ one }) => ({
    parent: one(page_compositions, {
      fields: [_page_compositions_v.parent],
      references: [page_compositions.id],
      relationName: "parent",
    }),
  }),
);
export const relations_payload_kv = relations(payload_kv, () => ({}));
export const relations_payload_folders_folder_type = relations(
  payload_folders_folder_type,
  ({ one }) => ({
    parent: one(payload_folders, {
      fields: [payload_folders_folder_type.parent],
      references: [payload_folders.id],
      relationName: "folderType",
    }),
  }),
);
export const relations_payload_folders = relations(
  payload_folders,
  ({ one, many }) => ({
    folder: one(payload_folders, {
      fields: [payload_folders.folder],
      references: [payload_folders.id],
      relationName: "folder",
    }),
    folderType: many(payload_folders_folder_type, {
      relationName: "folderType",
    }),
  }),
);
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: "_rels",
    }),
    pagesID: one(pages, {
      fields: [payload_locked_documents_rels.pagesID],
      references: [pages.id],
      relationName: "pages",
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: "media",
    }),
    "design-token-setsID": one(design_token_sets, {
      fields: [payload_locked_documents_rels["design-token-setsID"]],
      references: [design_token_sets.id],
      relationName: "design-token-sets",
    }),
    componentsID: one(components, {
      fields: [payload_locked_documents_rels.componentsID],
      references: [components.id],
      relationName: "components",
    }),
    "page-compositionsID": one(page_compositions, {
      fields: [payload_locked_documents_rels["page-compositionsID"]],
      references: [page_compositions.id],
      relationName: "page-compositions",
    }),
    "payload-foldersID": one(payload_folders, {
      fields: [payload_locked_documents_rels["payload-foldersID"]],
      references: [payload_folders.id],
      relationName: "payload-folders",
    }),
  }),
);
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
  }),
);
export const relations_payload_preferences = relations(
  payload_preferences,
  ({ many }) => ({
    _rels: many(payload_preferences_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_migrations = relations(
  payload_migrations,
  () => ({}),
);
export const relations_design_system_settings = relations(
  design_system_settings,
  ({ one }) => ({
    defaultTokenSet: one(design_token_sets, {
      fields: [design_system_settings.defaultTokenSet],
      references: [design_token_sets.id],
      relationName: "defaultTokenSet",
    }),
  }),
);

type DatabaseSchema = {
  enum_pages_blocks_hero_cta_link_type: typeof enum_pages_blocks_hero_cta_link_type;
  enum_pages_blocks_cta_button_link_type: typeof enum_pages_blocks_cta_button_link_type;
  enum_pages_status: typeof enum_pages_status;
  enum__pages_v_blocks_hero_cta_link_type: typeof enum__pages_v_blocks_hero_cta_link_type;
  enum__pages_v_blocks_cta_button_link_type: typeof enum__pages_v_blocks_cta_button_link_type;
  enum__pages_v_version_status: typeof enum__pages_v_version_status;
  enum_users_role: typeof enum_users_role;
  enum_design_token_sets_tokens_category: typeof enum_design_token_sets_tokens_category;
  enum_design_token_sets_tokens_mode: typeof enum_design_token_sets_tokens_mode;
  enum_design_token_sets_status: typeof enum_design_token_sets_status;
  enum__design_token_sets_v_version_tokens_category: typeof enum__design_token_sets_v_version_tokens_category;
  enum__design_token_sets_v_version_tokens_mode: typeof enum__design_token_sets_v_version_tokens_mode;
  enum__design_token_sets_v_version_status: typeof enum__design_token_sets_v_version_status;
  enum_components_block_type: typeof enum_components_block_type;
  enum_components_status: typeof enum_components_status;
  enum__components_v_version_block_type: typeof enum__components_v_version_block_type;
  enum__components_v_version_status: typeof enum__components_v_version_status;
  enum_page_compositions_status: typeof enum_page_compositions_status;
  enum__page_compositions_v_version_status: typeof enum__page_compositions_v_version_status;
  enum_payload_folders_folder_type: typeof enum_payload_folders_folder_type;
  enum_design_system_settings_active_color_mode: typeof enum_design_system_settings_active_color_mode;
  pages_blocks_hero: typeof pages_blocks_hero;
  pages_blocks_feature: typeof pages_blocks_feature;
  pages_blocks_cta: typeof pages_blocks_cta;
  pages_blocks_content: typeof pages_blocks_content;
  pages_content_slots: typeof pages_content_slots;
  pages: typeof pages;
  _pages_v_blocks_hero: typeof _pages_v_blocks_hero;
  _pages_v_blocks_feature: typeof _pages_v_blocks_feature;
  _pages_v_blocks_cta: typeof _pages_v_blocks_cta;
  _pages_v_blocks_content: typeof _pages_v_blocks_content;
  _pages_v_version_content_slots: typeof _pages_v_version_content_slots;
  _pages_v: typeof _pages_v;
  users_sessions: typeof users_sessions;
  users: typeof users;
  media: typeof media;
  design_token_sets_tokens: typeof design_token_sets_tokens;
  design_token_sets: typeof design_token_sets;
  _design_token_sets_v_version_tokens: typeof _design_token_sets_v_version_tokens;
  _design_token_sets_v: typeof _design_token_sets_v;
  components: typeof components;
  _components_v: typeof _components_v;
  page_compositions: typeof page_compositions;
  _page_compositions_v: typeof _page_compositions_v;
  payload_kv: typeof payload_kv;
  payload_folders_folder_type: typeof payload_folders_folder_type;
  payload_folders: typeof payload_folders;
  payload_locked_documents: typeof payload_locked_documents;
  payload_locked_documents_rels: typeof payload_locked_documents_rels;
  payload_preferences: typeof payload_preferences;
  payload_preferences_rels: typeof payload_preferences_rels;
  payload_migrations: typeof payload_migrations;
  design_system_settings: typeof design_system_settings;
  relations_pages_blocks_hero: typeof relations_pages_blocks_hero;
  relations_pages_blocks_feature: typeof relations_pages_blocks_feature;
  relations_pages_blocks_cta: typeof relations_pages_blocks_cta;
  relations_pages_blocks_content: typeof relations_pages_blocks_content;
  relations_pages_content_slots: typeof relations_pages_content_slots;
  relations_pages: typeof relations_pages;
  relations__pages_v_blocks_hero: typeof relations__pages_v_blocks_hero;
  relations__pages_v_blocks_feature: typeof relations__pages_v_blocks_feature;
  relations__pages_v_blocks_cta: typeof relations__pages_v_blocks_cta;
  relations__pages_v_blocks_content: typeof relations__pages_v_blocks_content;
  relations__pages_v_version_content_slots: typeof relations__pages_v_version_content_slots;
  relations__pages_v: typeof relations__pages_v;
  relations_users_sessions: typeof relations_users_sessions;
  relations_users: typeof relations_users;
  relations_media: typeof relations_media;
  relations_design_token_sets_tokens: typeof relations_design_token_sets_tokens;
  relations_design_token_sets: typeof relations_design_token_sets;
  relations__design_token_sets_v_version_tokens: typeof relations__design_token_sets_v_version_tokens;
  relations__design_token_sets_v: typeof relations__design_token_sets_v;
  relations_components: typeof relations_components;
  relations__components_v: typeof relations__components_v;
  relations_page_compositions: typeof relations_page_compositions;
  relations__page_compositions_v: typeof relations__page_compositions_v;
  relations_payload_kv: typeof relations_payload_kv;
  relations_payload_folders_folder_type: typeof relations_payload_folders_folder_type;
  relations_payload_folders: typeof relations_payload_folders;
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels;
  relations_payload_locked_documents: typeof relations_payload_locked_documents;
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels;
  relations_payload_preferences: typeof relations_payload_preferences;
  relations_payload_migrations: typeof relations_payload_migrations;
  relations_design_system_settings: typeof relations_design_system_settings;
};

declare module "@payloadcms/db-postgres" {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema;
  }
}
