import { z } from "zod";

export const STYLE_PROPERTY_KEYS = [
  "background",
  "borderColor",
  "borderRadius",
  "borderStyle",
  "borderWidth",
  "color",
  "fontFamily",
  "fontSize",
  "fontWeight",
  "textAlign",
  "lineHeight",
  "letterSpacing",
  "textTransform",
  "fontStyle",
  "textDecorationLine",
  "display",
  "flexDirection",
  "flexWrap",
  "justifyContent",
  "alignItems",
  "alignSelf",
  "flex",
  "flexGrow",
  "flexShrink",
  "flexBasis",
  "order",
  "overflow",
  "overflowX",
  "overflowY",
  "padding",
  "paddingTop",
  "paddingRight",
  "paddingBottom",
  "paddingLeft",
  "margin",
  "marginTop",
  "marginRight",
  "marginBottom",
  "marginLeft",
  "gap",
  "width",
  "height",
  "aspectRatio",
  "minWidth",
  "minHeight",
  "maxWidth",
  "maxHeight",
] as const;

export const StylePropertySchema = z.enum(STYLE_PROPERTY_KEYS);

export type StyleProperty = z.infer<typeof StylePropertySchema>;
