/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'design-token-sets': DesignTokenSet;
    'design-token-overrides': DesignTokenOverride;
    'component-definitions': ComponentDefinition;
    'component-revisions': ComponentRevision;
    'page-compositions': PageComposition;
    templates: Template;
    pages: Page;
    'release-snapshots': ReleaseSnapshot;
    'publish-jobs': PublishJob;
    'catalog-activity': CatalogActivity;
    'composition-presence': CompositionPresence;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'design-token-sets': DesignTokenSetsSelect<false> | DesignTokenSetsSelect<true>;
    'design-token-overrides': DesignTokenOverridesSelect<false> | DesignTokenOverridesSelect<true>;
    'component-definitions': ComponentDefinitionsSelect<false> | ComponentDefinitionsSelect<true>;
    'component-revisions': ComponentRevisionsSelect<false> | ComponentRevisionsSelect<true>;
    'page-compositions': PageCompositionsSelect<false> | PageCompositionsSelect<true>;
    templates: TemplatesSelect<false> | TemplatesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'release-snapshots': ReleaseSnapshotsSelect<false> | ReleaseSnapshotsSelect<true>;
    'publish-jobs': PublishJobsSelect<false> | PublishJobsSelect<true>;
    'catalog-activity': CatalogActivitySelect<false> | CatalogActivitySelect<true>;
    'composition-presence': CompositionPresenceSelect<false> | CompositionPresenceSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'design-system-settings': DesignSystemSetting;
  };
  globalsSelect: {
    'design-system-settings': DesignSystemSettingsSelect<false> | DesignSystemSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'admin' | 'designer' | 'contentEditor' | 'engineer';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Published token sets emit `design-system.token-published` for downstream compilation.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "design-token-sets".
 */
export interface DesignTokenSet {
  id: number;
  title: string;
  scopeKey: string;
  hasBeenPublished?: boolean | null;
  tokens: {
    key: string;
    category:
      | 'color'
      | 'space'
      | 'size'
      | 'radius'
      | 'typography'
      | 'shadow'
      | 'border'
      | 'zIndex'
      | 'opacity'
      | 'transition'
      | 'breakpoint'
      | 'container';
    resolvedValue: string;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "design-token-overrides".
 */
export interface DesignTokenOverride {
  id: number;
  tokenSet: number | DesignTokenSet;
  tokenKey: string;
  override:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "component-definitions".
 */
export interface ComponentDefinition {
  id: number;
  key: string;
  displayName: string;
  propContract:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  slotContract:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * When enabled, content editors can see this definition in the composer catalog. Leave off until the design is approved.
   */
  visibleInEditorCatalog?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "component-revisions".
 */
export interface ComponentRevision {
  id: number;
  definition: number | ComponentDefinition;
  label: string;
  propContract?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  slotContract?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  status: 'draft' | 'submitted' | 'approved' | 'published';
  /**
   * Breaking contract changes require dependency impact acknowledgment before publish (Phase 6).
   */
  isBreakingChange?: boolean | null;
  /**
   * Set when an approver acknowledges impacted pages (gateway or admin).
   */
  dependencyImpactAcknowledgedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Page composition tree (Phase 2). Lexical is not used for body layout.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-compositions".
 */
export interface PageComposition {
  id: number;
  title: string;
  slug: string;
  composition:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Set when the designer submits this composition for catalog review (gateway POST …/submit).
   */
  catalogSubmittedAt?: string | null;
  /**
   * Catalog approval gate (Phase 6). Page publish is blocked while submitted or rejected until approved.
   */
  catalogReviewStatus: 'none' | 'submitted' | 'approved' | 'rejected';
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Reusable starting points for Pages. Editors instantiate from approved templates.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "templates".
 */
export interface Template {
  id: number;
  title: string;
  slug: string;
  description?: string | null;
  /**
   * Composition copied when an editor creates a page from this template.
   */
  sourceComposition: number | PageComposition;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Public site page: references a page composition. Lexical fields are for page-level metadata only (SEO, social).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  pageComposition: number | PageComposition;
  /**
   * Metadata only — not composition body text.
   */
  seoDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Metadata only — not composition body text.
   */
  socialShareText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Point-in-time composition JSON captured when a page goes live.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "release-snapshots".
 */
export interface ReleaseSnapshot {
  id: number;
  page?: (number | null) | Page;
  pageComposition: number | PageComposition;
  snapshotComposition:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Deduped publish operations; succeeded + same key is a no-op.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publish-jobs".
 */
export interface PublishJob {
  id: number;
  idempotencyKey: string;
  kind: 'page_publish' | 'component_revision_publish' | 'rollback';
  status: 'pending' | 'succeeded' | 'failed';
  targetPage?: (number | null) | Page;
  targetRevision?: (number | null) | ComponentRevision;
  releaseSnapshot?: (number | null) | ReleaseSnapshot;
  errorMessage?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Publishing and catalog actions (Phase 6).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "catalog-activity".
 */
export interface CatalogActivity {
  id: number;
  resourceType: 'pageComposition' | 'componentRevision' | 'componentDefinition' | 'page';
  resourceId: string;
  action: 'submit' | 'approve' | 'reject' | 'publish' | 'rollback' | 'presence';
  actor?: (number | null) | User;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Heartbeat while a user has a composition open in the builder/composer.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "composition-presence".
 */
export interface CompositionPresence {
  id: number;
  composition: number | PageComposition;
  holder: number | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'design-token-sets';
        value: number | DesignTokenSet;
      } | null)
    | ({
        relationTo: 'design-token-overrides';
        value: number | DesignTokenOverride;
      } | null)
    | ({
        relationTo: 'component-definitions';
        value: number | ComponentDefinition;
      } | null)
    | ({
        relationTo: 'component-revisions';
        value: number | ComponentRevision;
      } | null)
    | ({
        relationTo: 'page-compositions';
        value: number | PageComposition;
      } | null)
    | ({
        relationTo: 'templates';
        value: number | Template;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'release-snapshots';
        value: number | ReleaseSnapshot;
      } | null)
    | ({
        relationTo: 'publish-jobs';
        value: number | PublishJob;
      } | null)
    | ({
        relationTo: 'catalog-activity';
        value: number | CatalogActivity;
      } | null)
    | ({
        relationTo: 'composition-presence';
        value: number | CompositionPresence;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "design-token-sets_select".
 */
export interface DesignTokenSetsSelect<T extends boolean = true> {
  title?: T;
  scopeKey?: T;
  hasBeenPublished?: T;
  tokens?:
    | T
    | {
        key?: T;
        category?: T;
        resolvedValue?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "design-token-overrides_select".
 */
export interface DesignTokenOverridesSelect<T extends boolean = true> {
  tokenSet?: T;
  tokenKey?: T;
  override?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "component-definitions_select".
 */
export interface ComponentDefinitionsSelect<T extends boolean = true> {
  key?: T;
  displayName?: T;
  propContract?: T;
  slotContract?: T;
  visibleInEditorCatalog?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "component-revisions_select".
 */
export interface ComponentRevisionsSelect<T extends boolean = true> {
  definition?: T;
  label?: T;
  propContract?: T;
  slotContract?: T;
  status?: T;
  isBreakingChange?: T;
  dependencyImpactAcknowledgedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-compositions_select".
 */
export interface PageCompositionsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  composition?: T;
  catalogSubmittedAt?: T;
  catalogReviewStatus?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "templates_select".
 */
export interface TemplatesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  sourceComposition?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  pageComposition?: T;
  seoDescription?: T;
  socialShareText?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "release-snapshots_select".
 */
export interface ReleaseSnapshotsSelect<T extends boolean = true> {
  page?: T;
  pageComposition?: T;
  snapshotComposition?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publish-jobs_select".
 */
export interface PublishJobsSelect<T extends boolean = true> {
  idempotencyKey?: T;
  kind?: T;
  status?: T;
  targetPage?: T;
  targetRevision?: T;
  releaseSnapshot?: T;
  errorMessage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "catalog-activity_select".
 */
export interface CatalogActivitySelect<T extends boolean = true> {
  resourceType?: T;
  resourceId?: T;
  action?: T;
  actor?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "composition-presence_select".
 */
export interface CompositionPresenceSelect<T extends boolean = true> {
  composition?: T;
  holder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Default published token set and active brand scope.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "design-system-settings".
 */
export interface DesignSystemSetting {
  id: number;
  defaultTokenSet?: (number | null) | DesignTokenSet;
  activeBrandKey?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "design-system-settings_select".
 */
export interface DesignSystemSettingsSelect<T extends boolean = true> {
  defaultTokenSet?: T;
  activeBrandKey?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}