/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from "@payloadcms/db-postgres";
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  varchar,
  jsonb,
  serial,
  timestamp,
  boolean,
  numeric,
  type AnyPgColumn,
  pgEnum,
} from "@payloadcms/db-postgres/drizzle/pg-core";
import { sql, relations } from "@payloadcms/db-postgres/drizzle";
export const enum_pages_status = pgEnum("enum_pages_status", [
  "draft",
  "published",
]);
export const enum__pages_v_version_status = pgEnum(
  "enum__pages_v_version_status",
  ["draft", "published"],
);
export const enum_users_role = pgEnum("enum_users_role", [
  "admin",
  "designer",
  "contentEditor",
  "engineer",
]);
export const enum_design_token_sets_tokens_category = pgEnum(
  "enum_design_token_sets_tokens_category",
  [
    "color",
    "space",
    "size",
    "radius",
    "typography",
    "shadow",
    "border",
    "zIndex",
    "opacity",
    "transition",
    "breakpoint",
    "container",
  ],
);
export const enum_design_token_sets_status = pgEnum(
  "enum_design_token_sets_status",
  ["draft", "published"],
);
export const enum__design_token_sets_v_version_tokens_category = pgEnum(
  "enum__design_token_sets_v_version_tokens_category",
  [
    "color",
    "space",
    "size",
    "radius",
    "typography",
    "shadow",
    "border",
    "zIndex",
    "opacity",
    "transition",
    "breakpoint",
    "container",
  ],
);
export const enum__design_token_sets_v_version_status = pgEnum(
  "enum__design_token_sets_v_version_status",
  ["draft", "published"],
);
export const enum_components_status = pgEnum("enum_components_status", [
  "draft",
  "published",
]);
export const enum__components_v_version_status = pgEnum(
  "enum__components_v_version_status",
  ["draft", "published"],
);
export const enum_page_compositions_catalog_review_status = pgEnum(
  "enum_page_compositions_catalog_review_status",
  ["none", "submitted", "approved", "rejected"],
);
export const enum_page_compositions_status = pgEnum(
  "enum_page_compositions_status",
  ["draft", "published"],
);
export const enum__page_compositions_v_version_catalog_review_status = pgEnum(
  "enum__page_compositions_v_version_catalog_review_status",
  ["none", "submitted", "approved", "rejected"],
);
export const enum__page_compositions_v_version_status = pgEnum(
  "enum__page_compositions_v_version_status",
  ["draft", "published"],
);
export const enum_publish_jobs_kind = pgEnum("enum_publish_jobs_kind", [
  "page_publish",
  "component_publish",
  "rollback",
]);
export const enum_publish_jobs_status = pgEnum("enum_publish_jobs_status", [
  "pending",
  "succeeded",
  "failed",
]);
export const enum_catalog_activity_resource_type = pgEnum(
  "enum_catalog_activity_resource_type",
  ["pageComposition", "componentRevision", "componentDefinition", "page"],
);
export const enum_catalog_activity_action = pgEnum(
  "enum_catalog_activity_action",
  ["submit", "approve", "reject", "publish", "rollback", "presence"],
);
export const enum_payload_folders_folder_type = pgEnum(
  "enum_payload_folders_folder_type",
  ["components"],
);

export const pages_content_slots_blocks = pgTable(
  "pages_content_slots_blocks",
  {
    _order: integer("_order").notNull(),
    _parentID: varchar("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    componentDefinition: integer("component_definition_id").references(
      () => components.id,
      {
        onDelete: "set null",
      },
    ),
    editorFieldValues: jsonb("editor_field_values").default(sql`'{}'::jsonb`),
  },
  (columns) => [
    index("pages_content_slots_blocks_order_idx").on(columns._order),
    index("pages_content_slots_blocks_parent_id_idx").on(columns._parentID),
    index("pages_content_slots_blocks_component_definition_idx").on(
      columns.componentDefinition,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [pages_content_slots.id],
      name: "pages_content_slots_blocks_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const pages_content_slots = pgTable(
  "pages_content_slots",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    slotId: varchar("slot_id"),
  },
  (columns) => [
    index("pages_content_slots_order_idx").on(columns._order),
    index("pages_content_slots_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [pages.id],
      name: "pages_content_slots_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const pages = pgTable(
  "pages",
  {
    id: serial("id").primaryKey(),
    title: varchar("title"),
    slug: varchar("slug"),
    pageComposition: integer("page_composition_id").references(
      () => page_compositions.id,
      {
        onDelete: "set null",
      },
    ),
    templateEditorFields: jsonb("template_editor_fields").default(
      sql`'{}'::jsonb`,
    ),
    seoDescription: jsonb("seo_description"),
    socialShareText: jsonb("social_share_text"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    _status: enum_pages_status("_status").default("draft"),
  },
  (columns) => [
    uniqueIndex("pages_slug_idx").on(columns.slug),
    index("pages_page_composition_idx").on(columns.pageComposition),
    index("pages_updated_at_idx").on(columns.updatedAt),
    index("pages_created_at_idx").on(columns.createdAt),
    index("pages__status_idx").on(columns._status),
  ],
);

export const _pages_v_version_content_slots_blocks = pgTable(
  "_pages_v_version_content_slots_blocks",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: serial("id").primaryKey(),
    componentDefinition: integer("component_definition_id").references(
      () => components.id,
      {
        onDelete: "set null",
      },
    ),
    editorFieldValues: jsonb("editor_field_values").default(sql`'{}'::jsonb`),
    _uuid: varchar("_uuid"),
  },
  (columns) => [
    index("_pages_v_version_content_slots_blocks_order_idx").on(columns._order),
    index("_pages_v_version_content_slots_blocks_parent_id_idx").on(
      columns._parentID,
    ),
    index("_pages_v_version_content_slots_blocks_component_definiti_idx").on(
      columns.componentDefinition,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [_pages_v_version_content_slots.id],
      name: "_pages_v_version_content_slots_blocks_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const _pages_v_version_content_slots = pgTable(
  "_pages_v_version_content_slots",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: serial("id").primaryKey(),
    slotId: varchar("slot_id"),
    _uuid: varchar("_uuid"),
  },
  (columns) => [
    index("_pages_v_version_content_slots_order_idx").on(columns._order),
    index("_pages_v_version_content_slots_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [_pages_v.id],
      name: "_pages_v_version_content_slots_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const _pages_v = pgTable(
  "_pages_v",
  {
    id: serial("id").primaryKey(),
    parent: integer("parent_id").references(() => pages.id, {
      onDelete: "set null",
    }),
    version_title: varchar("version_title"),
    version_slug: varchar("version_slug"),
    version_pageComposition: integer("version_page_composition_id").references(
      () => page_compositions.id,
      {
        onDelete: "set null",
      },
    ),
    version_templateEditorFields: jsonb(
      "version_template_editor_fields",
    ).default(sql`'{}'::jsonb`),
    version_seoDescription: jsonb("version_seo_description"),
    version_socialShareText: jsonb("version_social_share_text"),
    version_updatedAt: timestamp("version_updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp("version_created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version__status:
      enum__pages_v_version_status("version__status").default("draft"),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    latest: boolean("latest"),
  },
  (columns) => [
    index("_pages_v_parent_idx").on(columns.parent),
    index("_pages_v_version_version_slug_idx").on(columns.version_slug),
    index("_pages_v_version_version_page_composition_idx").on(
      columns.version_pageComposition,
    ),
    index("_pages_v_version_version_updated_at_idx").on(
      columns.version_updatedAt,
    ),
    index("_pages_v_version_version_created_at_idx").on(
      columns.version_createdAt,
    ),
    index("_pages_v_version_version__status_idx").on(columns.version__status),
    index("_pages_v_created_at_idx").on(columns.createdAt),
    index("_pages_v_updated_at_idx").on(columns.updatedAt),
    index("_pages_v_latest_idx").on(columns.latest),
  ],
);

export const users_sessions = pgTable(
  "users_sessions",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    expiresAt: timestamp("expires_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index("users_sessions_order_idx").on(columns._order),
    index("users_sessions_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [users.id],
      name: "users_sessions_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const users = pgTable(
  "users",
  {
    id: serial("id").primaryKey(),
    role: enum_users_role("role").notNull().default("contentEditor"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    email: varchar("email").notNull(),
    resetPasswordToken: varchar("reset_password_token"),
    resetPasswordExpiration: timestamp("reset_password_expiration", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar("salt"),
    hash: varchar("hash"),
    loginAttempts: numeric("login_attempts", { mode: "number" }).default(0),
    lockUntil: timestamp("lock_until", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => [
    index("users_updated_at_idx").on(columns.updatedAt),
    index("users_created_at_idx").on(columns.createdAt),
    uniqueIndex("users_email_idx").on(columns.email),
  ],
);

export const media = pgTable(
  "media",
  {
    id: serial("id").primaryKey(),
    alt: varchar("alt").notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    url: varchar("url"),
    thumbnailURL: varchar("thumbnail_u_r_l"),
    filename: varchar("filename"),
    mimeType: varchar("mime_type"),
    filesize: numeric("filesize", { mode: "number" }),
    width: numeric("width", { mode: "number" }),
    height: numeric("height", { mode: "number" }),
    focalX: numeric("focal_x", { mode: "number" }),
    focalY: numeric("focal_y", { mode: "number" }),
  },
  (columns) => [
    index("media_updated_at_idx").on(columns.updatedAt),
    index("media_created_at_idx").on(columns.createdAt),
    uniqueIndex("media_filename_idx").on(columns.filename),
  ],
);

export const design_token_sets_tokens = pgTable(
  "design_token_sets_tokens",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    key: varchar("key"),
    category: enum_design_token_sets_tokens_category("category"),
    resolvedValue: varchar("resolved_value"),
  },
  (columns) => [
    index("design_token_sets_tokens_order_idx").on(columns._order),
    index("design_token_sets_tokens_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [design_token_sets.id],
      name: "design_token_sets_tokens_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const design_token_sets = pgTable(
  "design_token_sets",
  {
    id: serial("id").primaryKey(),
    title: varchar("title"),
    scopeKey: varchar("scope_key"),
    hasBeenPublished: boolean("has_been_published").default(false),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    _status: enum_design_token_sets_status("_status").default("draft"),
  },
  (columns) => [
    uniqueIndex("design_token_sets_scope_key_idx").on(columns.scopeKey),
    index("design_token_sets_updated_at_idx").on(columns.updatedAt),
    index("design_token_sets_created_at_idx").on(columns.createdAt),
    index("design_token_sets__status_idx").on(columns._status),
  ],
);

export const _design_token_sets_v_version_tokens = pgTable(
  "_design_token_sets_v_version_tokens",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: serial("id").primaryKey(),
    key: varchar("key"),
    category: enum__design_token_sets_v_version_tokens_category("category"),
    resolvedValue: varchar("resolved_value"),
    _uuid: varchar("_uuid"),
  },
  (columns) => [
    index("_design_token_sets_v_version_tokens_order_idx").on(columns._order),
    index("_design_token_sets_v_version_tokens_parent_id_idx").on(
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [_design_token_sets_v.id],
      name: "_design_token_sets_v_version_tokens_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const _design_token_sets_v = pgTable(
  "_design_token_sets_v",
  {
    id: serial("id").primaryKey(),
    parent: integer("parent_id").references(() => design_token_sets.id, {
      onDelete: "set null",
    }),
    version_title: varchar("version_title"),
    version_scopeKey: varchar("version_scope_key"),
    version_hasBeenPublished: boolean("version_has_been_published").default(
      false,
    ),
    version_updatedAt: timestamp("version_updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp("version_created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version__status:
      enum__design_token_sets_v_version_status("version__status").default(
        "draft",
      ),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    latest: boolean("latest"),
  },
  (columns) => [
    index("_design_token_sets_v_parent_idx").on(columns.parent),
    index("_design_token_sets_v_version_version_scope_key_idx").on(
      columns.version_scopeKey,
    ),
    index("_design_token_sets_v_version_version_updated_at_idx").on(
      columns.version_updatedAt,
    ),
    index("_design_token_sets_v_version_version_created_at_idx").on(
      columns.version_createdAt,
    ),
    index("_design_token_sets_v_version_version__status_idx").on(
      columns.version__status,
    ),
    index("_design_token_sets_v_created_at_idx").on(columns.createdAt),
    index("_design_token_sets_v_updated_at_idx").on(columns.updatedAt),
    index("_design_token_sets_v_latest_idx").on(columns.latest),
  ],
);

export const design_token_overrides = pgTable(
  "design_token_overrides",
  {
    id: serial("id").primaryKey(),
    tokenSet: integer("token_set_id")
      .notNull()
      .references(() => design_token_sets.id, {
        onDelete: "set null",
      }),
    tokenKey: varchar("token_key").notNull(),
    override: jsonb("override").notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("design_token_overrides_token_set_idx").on(columns.tokenSet),
    index("design_token_overrides_updated_at_idx").on(columns.updatedAt),
    index("design_token_overrides_created_at_idx").on(columns.createdAt),
  ],
);

export const components = pgTable(
  "components",
  {
    id: serial("id").primaryKey(),
    displayName: varchar("display_name"),
    key: varchar("key"),
    propContract: jsonb("prop_contract"),
    editorFields: jsonb("editor_fields"),
    composition: jsonb("composition"),
    lastTouchedBy: integer("last_touched_by_id").references(() => users.id, {
      onDelete: "set null",
    }),
    folder: integer("folder_id").references(() => payload_folders.id, {
      onDelete: "set null",
    }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    _status: enum_components_status("_status").default("draft"),
  },
  (columns) => [
    uniqueIndex("components_key_idx").on(columns.key),
    index("components_last_touched_by_idx").on(columns.lastTouchedBy),
    index("components_folder_idx").on(columns.folder),
    index("components_updated_at_idx").on(columns.updatedAt),
    index("components_created_at_idx").on(columns.createdAt),
    index("components__status_idx").on(columns._status),
  ],
);

export const _components_v = pgTable(
  "_components_v",
  {
    id: serial("id").primaryKey(),
    parent: integer("parent_id").references(() => components.id, {
      onDelete: "set null",
    }),
    version_displayName: varchar("version_display_name"),
    version_key: varchar("version_key"),
    version_propContract: jsonb("version_prop_contract"),
    version_editorFields: jsonb("version_editor_fields"),
    version_composition: jsonb("version_composition"),
    version_lastTouchedBy: integer("version_last_touched_by_id").references(
      () => users.id,
      {
        onDelete: "set null",
      },
    ),
    version_folder: integer("version_folder_id").references(
      () => payload_folders.id,
      {
        onDelete: "set null",
      },
    ),
    version_updatedAt: timestamp("version_updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp("version_created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version__status:
      enum__components_v_version_status("version__status").default("draft"),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    latest: boolean("latest"),
  },
  (columns) => [
    index("_components_v_parent_idx").on(columns.parent),
    index("_components_v_version_version_key_idx").on(columns.version_key),
    index("_components_v_version_version_last_touched_by_idx").on(
      columns.version_lastTouchedBy,
    ),
    index("_components_v_version_version_folder_idx").on(
      columns.version_folder,
    ),
    index("_components_v_version_version_updated_at_idx").on(
      columns.version_updatedAt,
    ),
    index("_components_v_version_version_created_at_idx").on(
      columns.version_createdAt,
    ),
    index("_components_v_version_version__status_idx").on(
      columns.version__status,
    ),
    index("_components_v_created_at_idx").on(columns.createdAt),
    index("_components_v_updated_at_idx").on(columns.updatedAt),
    index("_components_v_latest_idx").on(columns.latest),
  ],
);

export const page_compositions = pgTable(
  "page_compositions",
  {
    id: serial("id").primaryKey(),
    title: varchar("title"),
    slug: varchar("slug"),
    composition: jsonb("composition"),
    catalogSubmittedAt: timestamp("catalog_submitted_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    catalogReviewStatus: enum_page_compositions_catalog_review_status(
      "catalog_review_status",
    ).default("none"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    _status: enum_page_compositions_status("_status").default("draft"),
  },
  (columns) => [
    uniqueIndex("page_compositions_slug_idx").on(columns.slug),
    index("page_compositions_updated_at_idx").on(columns.updatedAt),
    index("page_compositions_created_at_idx").on(columns.createdAt),
    index("page_compositions__status_idx").on(columns._status),
  ],
);

export const _page_compositions_v = pgTable(
  "_page_compositions_v",
  {
    id: serial("id").primaryKey(),
    parent: integer("parent_id").references(() => page_compositions.id, {
      onDelete: "set null",
    }),
    version_title: varchar("version_title"),
    version_slug: varchar("version_slug"),
    version_composition: jsonb("version_composition"),
    version_catalogSubmittedAt: timestamp("version_catalog_submitted_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_catalogReviewStatus:
      enum__page_compositions_v_version_catalog_review_status(
        "version_catalog_review_status",
      ).default("none"),
    version_updatedAt: timestamp("version_updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp("version_created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version__status:
      enum__page_compositions_v_version_status("version__status").default(
        "draft",
      ),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    latest: boolean("latest"),
  },
  (columns) => [
    index("_page_compositions_v_parent_idx").on(columns.parent),
    index("_page_compositions_v_version_version_slug_idx").on(
      columns.version_slug,
    ),
    index("_page_compositions_v_version_version_updated_at_idx").on(
      columns.version_updatedAt,
    ),
    index("_page_compositions_v_version_version_created_at_idx").on(
      columns.version_createdAt,
    ),
    index("_page_compositions_v_version_version__status_idx").on(
      columns.version__status,
    ),
    index("_page_compositions_v_created_at_idx").on(columns.createdAt),
    index("_page_compositions_v_updated_at_idx").on(columns.updatedAt),
    index("_page_compositions_v_latest_idx").on(columns.latest),
  ],
);

export const release_snapshots = pgTable(
  "release_snapshots",
  {
    id: serial("id").primaryKey(),
    page: integer("page_id").references(() => pages.id, {
      onDelete: "set null",
    }),
    pageComposition: integer("page_composition_id")
      .notNull()
      .references(() => page_compositions.id, {
        onDelete: "set null",
      }),
    snapshotComposition: jsonb("snapshot_composition").notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("release_snapshots_page_idx").on(columns.page),
    index("release_snapshots_page_composition_idx").on(columns.pageComposition),
    index("release_snapshots_updated_at_idx").on(columns.updatedAt),
    index("release_snapshots_created_at_idx").on(columns.createdAt),
  ],
);

export const publish_jobs = pgTable(
  "publish_jobs",
  {
    id: serial("id").primaryKey(),
    idempotencyKey: varchar("idempotency_key").notNull(),
    kind: enum_publish_jobs_kind("kind").notNull(),
    status: enum_publish_jobs_status("status").notNull().default("pending"),
    targetPage: integer("target_page_id").references(() => pages.id, {
      onDelete: "set null",
    }),
    targetComponent: integer("target_component_id").references(
      () => components.id,
      {
        onDelete: "set null",
      },
    ),
    releaseSnapshot: integer("release_snapshot_id").references(
      () => release_snapshots.id,
      {
        onDelete: "set null",
      },
    ),
    errorMessage: varchar("error_message"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("publish_jobs_idempotency_key_idx").on(columns.idempotencyKey),
    index("publish_jobs_target_page_idx").on(columns.targetPage),
    index("publish_jobs_target_component_idx").on(columns.targetComponent),
    index("publish_jobs_release_snapshot_idx").on(columns.releaseSnapshot),
    index("publish_jobs_updated_at_idx").on(columns.updatedAt),
    index("publish_jobs_created_at_idx").on(columns.createdAt),
  ],
);

export const catalog_activity = pgTable(
  "catalog_activity",
  {
    id: serial("id").primaryKey(),
    resourceType:
      enum_catalog_activity_resource_type("resource_type").notNull(),
    resourceId: varchar("resource_id").notNull(),
    action: enum_catalog_activity_action("action").notNull(),
    actor: integer("actor_id").references(() => users.id, {
      onDelete: "set null",
    }),
    metadata: jsonb("metadata"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("catalog_activity_resource_id_idx").on(columns.resourceId),
    index("catalog_activity_actor_idx").on(columns.actor),
    index("catalog_activity_updated_at_idx").on(columns.updatedAt),
    index("catalog_activity_created_at_idx").on(columns.createdAt),
  ],
);

export const composition_presence = pgTable(
  "composition_presence",
  {
    id: serial("id").primaryKey(),
    composition: integer("composition_id")
      .notNull()
      .references(() => page_compositions.id, {
        onDelete: "set null",
      }),
    holder: integer("holder_id")
      .notNull()
      .references(() => users.id, {
        onDelete: "set null",
      }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("composition_presence_composition_idx").on(columns.composition),
    index("composition_presence_holder_idx").on(columns.holder),
    index("composition_presence_updated_at_idx").on(columns.updatedAt),
    index("composition_presence_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_kv = pgTable(
  "payload_kv",
  {
    id: serial("id").primaryKey(),
    key: varchar("key").notNull(),
    data: jsonb("data").notNull(),
  },
  (columns) => [uniqueIndex("payload_kv_key_idx").on(columns.key)],
);

export const payload_folders_folder_type = pgTable(
  "payload_folders_folder_type",
  {
    order: integer("order").notNull(),
    parent: integer("parent_id").notNull(),
    value: enum_payload_folders_folder_type("value"),
    id: serial("id").primaryKey(),
  },
  (columns) => [
    index("payload_folders_folder_type_order_idx").on(columns.order),
    index("payload_folders_folder_type_parent_idx").on(columns.parent),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_folders.id],
      name: "payload_folders_folder_type_parent_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_folders = pgTable(
  "payload_folders",
  {
    id: serial("id").primaryKey(),
    name: varchar("name").notNull(),
    folder: integer("folder_id").references(
      (): AnyPgColumn => payload_folders.id,
      {
        onDelete: "set null",
      },
    ),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_folders_name_idx").on(columns.name),
    index("payload_folders_folder_idx").on(columns.folder),
    index("payload_folders_updated_at_idx").on(columns.updatedAt),
    index("payload_folders_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_locked_documents = pgTable(
  "payload_locked_documents",
  {
    id: serial("id").primaryKey(),
    globalSlug: varchar("global_slug"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_locked_documents_global_slug_idx").on(columns.globalSlug),
    index("payload_locked_documents_updated_at_idx").on(columns.updatedAt),
    index("payload_locked_documents_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_locked_documents_rels = pgTable(
  "payload_locked_documents_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    pagesID: integer("pages_id"),
    usersID: integer("users_id"),
    mediaID: integer("media_id"),
    "design-token-setsID": integer("design_token_sets_id"),
    "design-token-overridesID": integer("design_token_overrides_id"),
    componentsID: integer("components_id"),
    "page-compositionsID": integer("page_compositions_id"),
    "release-snapshotsID": integer("release_snapshots_id"),
    "publish-jobsID": integer("publish_jobs_id"),
    "catalog-activityID": integer("catalog_activity_id"),
    "composition-presenceID": integer("composition_presence_id"),
    "payload-foldersID": integer("payload_folders_id"),
  },
  (columns) => [
    index("payload_locked_documents_rels_order_idx").on(columns.order),
    index("payload_locked_documents_rels_parent_idx").on(columns.parent),
    index("payload_locked_documents_rels_path_idx").on(columns.path),
    index("payload_locked_documents_rels_pages_id_idx").on(columns.pagesID),
    index("payload_locked_documents_rels_users_id_idx").on(columns.usersID),
    index("payload_locked_documents_rels_media_id_idx").on(columns.mediaID),
    index("payload_locked_documents_rels_design_token_sets_id_idx").on(
      columns["design-token-setsID"],
    ),
    index("payload_locked_documents_rels_design_token_overrides_id_idx").on(
      columns["design-token-overridesID"],
    ),
    index("payload_locked_documents_rels_components_id_idx").on(
      columns.componentsID,
    ),
    index("payload_locked_documents_rels_page_compositions_id_idx").on(
      columns["page-compositionsID"],
    ),
    index("payload_locked_documents_rels_release_snapshots_id_idx").on(
      columns["release-snapshotsID"],
    ),
    index("payload_locked_documents_rels_publish_jobs_id_idx").on(
      columns["publish-jobsID"],
    ),
    index("payload_locked_documents_rels_catalog_activity_id_idx").on(
      columns["catalog-activityID"],
    ),
    index("payload_locked_documents_rels_composition_presence_id_idx").on(
      columns["composition-presenceID"],
    ),
    index("payload_locked_documents_rels_payload_folders_id_idx").on(
      columns["payload-foldersID"],
    ),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_locked_documents.id],
      name: "payload_locked_documents_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["pagesID"]],
      foreignColumns: [pages.id],
      name: "payload_locked_documents_rels_pages_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_locked_documents_rels_users_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["mediaID"]],
      foreignColumns: [media.id],
      name: "payload_locked_documents_rels_media_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["design-token-setsID"]],
      foreignColumns: [design_token_sets.id],
      name: "payload_locked_documents_rels_design_token_sets_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["design-token-overridesID"]],
      foreignColumns: [design_token_overrides.id],
      name: "payload_locked_documents_rels_design_token_overrides_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["componentsID"]],
      foreignColumns: [components.id],
      name: "payload_locked_documents_rels_components_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["page-compositionsID"]],
      foreignColumns: [page_compositions.id],
      name: "payload_locked_documents_rels_page_compositions_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["release-snapshotsID"]],
      foreignColumns: [release_snapshots.id],
      name: "payload_locked_documents_rels_release_snapshots_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["publish-jobsID"]],
      foreignColumns: [publish_jobs.id],
      name: "payload_locked_documents_rels_publish_jobs_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["catalog-activityID"]],
      foreignColumns: [catalog_activity.id],
      name: "payload_locked_documents_rels_catalog_activity_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["composition-presenceID"]],
      foreignColumns: [composition_presence.id],
      name: "payload_locked_documents_rels_composition_presence_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["payload-foldersID"]],
      foreignColumns: [payload_folders.id],
      name: "payload_locked_documents_rels_payload_folders_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_preferences = pgTable(
  "payload_preferences",
  {
    id: serial("id").primaryKey(),
    key: varchar("key"),
    value: jsonb("value"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_preferences_key_idx").on(columns.key),
    index("payload_preferences_updated_at_idx").on(columns.updatedAt),
    index("payload_preferences_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_preferences_rels = pgTable(
  "payload_preferences_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: integer("users_id"),
  },
  (columns) => [
    index("payload_preferences_rels_order_idx").on(columns.order),
    index("payload_preferences_rels_parent_idx").on(columns.parent),
    index("payload_preferences_rels_path_idx").on(columns.path),
    index("payload_preferences_rels_users_id_idx").on(columns.usersID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_preferences.id],
      name: "payload_preferences_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_preferences_rels_users_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_migrations = pgTable(
  "payload_migrations",
  {
    id: serial("id").primaryKey(),
    name: varchar("name"),
    batch: numeric("batch", { mode: "number" }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_migrations_updated_at_idx").on(columns.updatedAt),
    index("payload_migrations_created_at_idx").on(columns.createdAt),
  ],
);

export const design_system_settings = pgTable(
  "design_system_settings",
  {
    id: serial("id").primaryKey(),
    defaultTokenSet: integer("default_token_set_id").references(
      () => design_token_sets.id,
      {
        onDelete: "set null",
      },
    ),
    activeBrandKey: varchar("active_brand_key"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => [
    index("design_system_settings_default_token_set_idx").on(
      columns.defaultTokenSet,
    ),
  ],
);

export const relations_pages_content_slots_blocks = relations(
  pages_content_slots_blocks,
  ({ one }) => ({
    _parentID: one(pages_content_slots, {
      fields: [pages_content_slots_blocks._parentID],
      references: [pages_content_slots.id],
      relationName: "blocks",
    }),
    componentDefinition: one(components, {
      fields: [pages_content_slots_blocks.componentDefinition],
      references: [components.id],
      relationName: "componentDefinition",
    }),
  }),
);
export const relations_pages_content_slots = relations(
  pages_content_slots,
  ({ one, many }) => ({
    _parentID: one(pages, {
      fields: [pages_content_slots._parentID],
      references: [pages.id],
      relationName: "contentSlots",
    }),
    blocks: many(pages_content_slots_blocks, {
      relationName: "blocks",
    }),
  }),
);
export const relations_pages = relations(pages, ({ one, many }) => ({
  pageComposition: one(page_compositions, {
    fields: [pages.pageComposition],
    references: [page_compositions.id],
    relationName: "pageComposition",
  }),
  contentSlots: many(pages_content_slots, {
    relationName: "contentSlots",
  }),
}));
export const relations__pages_v_version_content_slots_blocks = relations(
  _pages_v_version_content_slots_blocks,
  ({ one }) => ({
    _parentID: one(_pages_v_version_content_slots, {
      fields: [_pages_v_version_content_slots_blocks._parentID],
      references: [_pages_v_version_content_slots.id],
      relationName: "blocks",
    }),
    componentDefinition: one(components, {
      fields: [_pages_v_version_content_slots_blocks.componentDefinition],
      references: [components.id],
      relationName: "componentDefinition",
    }),
  }),
);
export const relations__pages_v_version_content_slots = relations(
  _pages_v_version_content_slots,
  ({ one, many }) => ({
    _parentID: one(_pages_v, {
      fields: [_pages_v_version_content_slots._parentID],
      references: [_pages_v.id],
      relationName: "version_contentSlots",
    }),
    blocks: many(_pages_v_version_content_slots_blocks, {
      relationName: "blocks",
    }),
  }),
);
export const relations__pages_v = relations(_pages_v, ({ one, many }) => ({
  parent: one(pages, {
    fields: [_pages_v.parent],
    references: [pages.id],
    relationName: "parent",
  }),
  version_pageComposition: one(page_compositions, {
    fields: [_pages_v.version_pageComposition],
    references: [page_compositions.id],
    relationName: "version_pageComposition",
  }),
  version_contentSlots: many(_pages_v_version_content_slots, {
    relationName: "version_contentSlots",
  }),
}));
export const relations_users_sessions = relations(
  users_sessions,
  ({ one }) => ({
    _parentID: one(users, {
      fields: [users_sessions._parentID],
      references: [users.id],
      relationName: "sessions",
    }),
  }),
);
export const relations_users = relations(users, ({ many }) => ({
  sessions: many(users_sessions, {
    relationName: "sessions",
  }),
}));
export const relations_media = relations(media, () => ({}));
export const relations_design_token_sets_tokens = relations(
  design_token_sets_tokens,
  ({ one }) => ({
    _parentID: one(design_token_sets, {
      fields: [design_token_sets_tokens._parentID],
      references: [design_token_sets.id],
      relationName: "tokens",
    }),
  }),
);
export const relations_design_token_sets = relations(
  design_token_sets,
  ({ many }) => ({
    tokens: many(design_token_sets_tokens, {
      relationName: "tokens",
    }),
  }),
);
export const relations__design_token_sets_v_version_tokens = relations(
  _design_token_sets_v_version_tokens,
  ({ one }) => ({
    _parentID: one(_design_token_sets_v, {
      fields: [_design_token_sets_v_version_tokens._parentID],
      references: [_design_token_sets_v.id],
      relationName: "version_tokens",
    }),
  }),
);
export const relations__design_token_sets_v = relations(
  _design_token_sets_v,
  ({ one, many }) => ({
    parent: one(design_token_sets, {
      fields: [_design_token_sets_v.parent],
      references: [design_token_sets.id],
      relationName: "parent",
    }),
    version_tokens: many(_design_token_sets_v_version_tokens, {
      relationName: "version_tokens",
    }),
  }),
);
export const relations_design_token_overrides = relations(
  design_token_overrides,
  ({ one }) => ({
    tokenSet: one(design_token_sets, {
      fields: [design_token_overrides.tokenSet],
      references: [design_token_sets.id],
      relationName: "tokenSet",
    }),
  }),
);
export const relations_components = relations(components, ({ one }) => ({
  lastTouchedBy: one(users, {
    fields: [components.lastTouchedBy],
    references: [users.id],
    relationName: "lastTouchedBy",
  }),
  folder: one(payload_folders, {
    fields: [components.folder],
    references: [payload_folders.id],
    relationName: "folder",
  }),
}));
export const relations__components_v = relations(_components_v, ({ one }) => ({
  parent: one(components, {
    fields: [_components_v.parent],
    references: [components.id],
    relationName: "parent",
  }),
  version_lastTouchedBy: one(users, {
    fields: [_components_v.version_lastTouchedBy],
    references: [users.id],
    relationName: "version_lastTouchedBy",
  }),
  version_folder: one(payload_folders, {
    fields: [_components_v.version_folder],
    references: [payload_folders.id],
    relationName: "version_folder",
  }),
}));
export const relations_page_compositions = relations(
  page_compositions,
  () => ({}),
);
export const relations__page_compositions_v = relations(
  _page_compositions_v,
  ({ one }) => ({
    parent: one(page_compositions, {
      fields: [_page_compositions_v.parent],
      references: [page_compositions.id],
      relationName: "parent",
    }),
  }),
);
export const relations_release_snapshots = relations(
  release_snapshots,
  ({ one }) => ({
    page: one(pages, {
      fields: [release_snapshots.page],
      references: [pages.id],
      relationName: "page",
    }),
    pageComposition: one(page_compositions, {
      fields: [release_snapshots.pageComposition],
      references: [page_compositions.id],
      relationName: "pageComposition",
    }),
  }),
);
export const relations_publish_jobs = relations(publish_jobs, ({ one }) => ({
  targetPage: one(pages, {
    fields: [publish_jobs.targetPage],
    references: [pages.id],
    relationName: "targetPage",
  }),
  targetComponent: one(components, {
    fields: [publish_jobs.targetComponent],
    references: [components.id],
    relationName: "targetComponent",
  }),
  releaseSnapshot: one(release_snapshots, {
    fields: [publish_jobs.releaseSnapshot],
    references: [release_snapshots.id],
    relationName: "releaseSnapshot",
  }),
}));
export const relations_catalog_activity = relations(
  catalog_activity,
  ({ one }) => ({
    actor: one(users, {
      fields: [catalog_activity.actor],
      references: [users.id],
      relationName: "actor",
    }),
  }),
);
export const relations_composition_presence = relations(
  composition_presence,
  ({ one }) => ({
    composition: one(page_compositions, {
      fields: [composition_presence.composition],
      references: [page_compositions.id],
      relationName: "composition",
    }),
    holder: one(users, {
      fields: [composition_presence.holder],
      references: [users.id],
      relationName: "holder",
    }),
  }),
);
export const relations_payload_kv = relations(payload_kv, () => ({}));
export const relations_payload_folders_folder_type = relations(
  payload_folders_folder_type,
  ({ one }) => ({
    parent: one(payload_folders, {
      fields: [payload_folders_folder_type.parent],
      references: [payload_folders.id],
      relationName: "folderType",
    }),
  }),
);
export const relations_payload_folders = relations(
  payload_folders,
  ({ one, many }) => ({
    folder: one(payload_folders, {
      fields: [payload_folders.folder],
      references: [payload_folders.id],
      relationName: "folder",
    }),
    folderType: many(payload_folders_folder_type, {
      relationName: "folderType",
    }),
  }),
);
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: "_rels",
    }),
    pagesID: one(pages, {
      fields: [payload_locked_documents_rels.pagesID],
      references: [pages.id],
      relationName: "pages",
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: "media",
    }),
    "design-token-setsID": one(design_token_sets, {
      fields: [payload_locked_documents_rels["design-token-setsID"]],
      references: [design_token_sets.id],
      relationName: "design-token-sets",
    }),
    "design-token-overridesID": one(design_token_overrides, {
      fields: [payload_locked_documents_rels["design-token-overridesID"]],
      references: [design_token_overrides.id],
      relationName: "design-token-overrides",
    }),
    componentsID: one(components, {
      fields: [payload_locked_documents_rels.componentsID],
      references: [components.id],
      relationName: "components",
    }),
    "page-compositionsID": one(page_compositions, {
      fields: [payload_locked_documents_rels["page-compositionsID"]],
      references: [page_compositions.id],
      relationName: "page-compositions",
    }),
    "release-snapshotsID": one(release_snapshots, {
      fields: [payload_locked_documents_rels["release-snapshotsID"]],
      references: [release_snapshots.id],
      relationName: "release-snapshots",
    }),
    "publish-jobsID": one(publish_jobs, {
      fields: [payload_locked_documents_rels["publish-jobsID"]],
      references: [publish_jobs.id],
      relationName: "publish-jobs",
    }),
    "catalog-activityID": one(catalog_activity, {
      fields: [payload_locked_documents_rels["catalog-activityID"]],
      references: [catalog_activity.id],
      relationName: "catalog-activity",
    }),
    "composition-presenceID": one(composition_presence, {
      fields: [payload_locked_documents_rels["composition-presenceID"]],
      references: [composition_presence.id],
      relationName: "composition-presence",
    }),
    "payload-foldersID": one(payload_folders, {
      fields: [payload_locked_documents_rels["payload-foldersID"]],
      references: [payload_folders.id],
      relationName: "payload-folders",
    }),
  }),
);
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
  }),
);
export const relations_payload_preferences = relations(
  payload_preferences,
  ({ many }) => ({
    _rels: many(payload_preferences_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_migrations = relations(
  payload_migrations,
  () => ({}),
);
export const relations_design_system_settings = relations(
  design_system_settings,
  ({ one }) => ({
    defaultTokenSet: one(design_token_sets, {
      fields: [design_system_settings.defaultTokenSet],
      references: [design_token_sets.id],
      relationName: "defaultTokenSet",
    }),
  }),
);

type DatabaseSchema = {
  enum_pages_status: typeof enum_pages_status;
  enum__pages_v_version_status: typeof enum__pages_v_version_status;
  enum_users_role: typeof enum_users_role;
  enum_design_token_sets_tokens_category: typeof enum_design_token_sets_tokens_category;
  enum_design_token_sets_status: typeof enum_design_token_sets_status;
  enum__design_token_sets_v_version_tokens_category: typeof enum__design_token_sets_v_version_tokens_category;
  enum__design_token_sets_v_version_status: typeof enum__design_token_sets_v_version_status;
  enum_components_status: typeof enum_components_status;
  enum__components_v_version_status: typeof enum__components_v_version_status;
  enum_page_compositions_catalog_review_status: typeof enum_page_compositions_catalog_review_status;
  enum_page_compositions_status: typeof enum_page_compositions_status;
  enum__page_compositions_v_version_catalog_review_status: typeof enum__page_compositions_v_version_catalog_review_status;
  enum__page_compositions_v_version_status: typeof enum__page_compositions_v_version_status;
  enum_publish_jobs_kind: typeof enum_publish_jobs_kind;
  enum_publish_jobs_status: typeof enum_publish_jobs_status;
  enum_catalog_activity_resource_type: typeof enum_catalog_activity_resource_type;
  enum_catalog_activity_action: typeof enum_catalog_activity_action;
  enum_payload_folders_folder_type: typeof enum_payload_folders_folder_type;
  pages_content_slots_blocks: typeof pages_content_slots_blocks;
  pages_content_slots: typeof pages_content_slots;
  pages: typeof pages;
  _pages_v_version_content_slots_blocks: typeof _pages_v_version_content_slots_blocks;
  _pages_v_version_content_slots: typeof _pages_v_version_content_slots;
  _pages_v: typeof _pages_v;
  users_sessions: typeof users_sessions;
  users: typeof users;
  media: typeof media;
  design_token_sets_tokens: typeof design_token_sets_tokens;
  design_token_sets: typeof design_token_sets;
  _design_token_sets_v_version_tokens: typeof _design_token_sets_v_version_tokens;
  _design_token_sets_v: typeof _design_token_sets_v;
  design_token_overrides: typeof design_token_overrides;
  components: typeof components;
  _components_v: typeof _components_v;
  page_compositions: typeof page_compositions;
  _page_compositions_v: typeof _page_compositions_v;
  release_snapshots: typeof release_snapshots;
  publish_jobs: typeof publish_jobs;
  catalog_activity: typeof catalog_activity;
  composition_presence: typeof composition_presence;
  payload_kv: typeof payload_kv;
  payload_folders_folder_type: typeof payload_folders_folder_type;
  payload_folders: typeof payload_folders;
  payload_locked_documents: typeof payload_locked_documents;
  payload_locked_documents_rels: typeof payload_locked_documents_rels;
  payload_preferences: typeof payload_preferences;
  payload_preferences_rels: typeof payload_preferences_rels;
  payload_migrations: typeof payload_migrations;
  design_system_settings: typeof design_system_settings;
  relations_pages_content_slots_blocks: typeof relations_pages_content_slots_blocks;
  relations_pages_content_slots: typeof relations_pages_content_slots;
  relations_pages: typeof relations_pages;
  relations__pages_v_version_content_slots_blocks: typeof relations__pages_v_version_content_slots_blocks;
  relations__pages_v_version_content_slots: typeof relations__pages_v_version_content_slots;
  relations__pages_v: typeof relations__pages_v;
  relations_users_sessions: typeof relations_users_sessions;
  relations_users: typeof relations_users;
  relations_media: typeof relations_media;
  relations_design_token_sets_tokens: typeof relations_design_token_sets_tokens;
  relations_design_token_sets: typeof relations_design_token_sets;
  relations__design_token_sets_v_version_tokens: typeof relations__design_token_sets_v_version_tokens;
  relations__design_token_sets_v: typeof relations__design_token_sets_v;
  relations_design_token_overrides: typeof relations_design_token_overrides;
  relations_components: typeof relations_components;
  relations__components_v: typeof relations__components_v;
  relations_page_compositions: typeof relations_page_compositions;
  relations__page_compositions_v: typeof relations__page_compositions_v;
  relations_release_snapshots: typeof relations_release_snapshots;
  relations_publish_jobs: typeof relations_publish_jobs;
  relations_catalog_activity: typeof relations_catalog_activity;
  relations_composition_presence: typeof relations_composition_presence;
  relations_payload_kv: typeof relations_payload_kv;
  relations_payload_folders_folder_type: typeof relations_payload_folders_folder_type;
  relations_payload_folders: typeof relations_payload_folders;
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels;
  relations_payload_locked_documents: typeof relations_payload_locked_documents;
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels;
  relations_payload_preferences: typeof relations_payload_preferences;
  relations_payload_migrations: typeof relations_payload_migrations;
  relations_design_system_settings: typeof relations_design_system_settings;
};

declare module "@payloadcms/db-postgres" {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema;
  }
}
